# Adapted from https://github.com/rust-lang/libc/blob/master/.cirrus.yml

freebsd_instance:
  image_family: freebsd-13-1

task:
  name: x86_unknown-freebsd
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh --default-toolchain stable -y --profile=minimal
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo test
