[package]
name = "sap"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Straightforward Argument Parser"
license = "MIT OR Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
repository = "https://github.com/morr0ne/sap"
readme = "README.md"
documentation = "https://docs.rs/sap"
include = ["src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]

[features]
default = ["std"]
std = []

[target.'cfg(windows)'.dependencies]
windows = { version = "0.39.0", features = ["Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_Foundation", "Win32_System_Kernel"] }

[dev-dependencies]
libc = { version = "0.2.126", default-features = false }

[profile.release]
lto = true
codegen-units = 1
strip = true
# panic = "abort"
