[package]
name = "sap"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[target.'cfg(windows)'.dependencies]
windows = { version = "0.39.0", features = ["Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_Foundation", "Win32_System_Kernel"] }

[dev-dependencies]
argh = "0.1.8"
clap = { version = "3.2.15", default-features = false, features = ["derive", "std"] }
os_str_bytes = "6.2.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
# panic = "abort"

[package.metadata.cross.target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross:local"
