[package]
name = "sap_macros"
version = "0.1.0-alpha.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = { version = "1.0.99", default-features = false, features = ["parsing", "proc-macro"] }
