name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Run test on ${{matrix.os}} with rust ${{matrix.rust}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu, macos, windows]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo test
